name: Deploy ASP.NET API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Change if using a different .NET version

      - name: Build API
        run: dotnet publish -c Release -o out

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-api
          path: out/

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
